### ISSUE TITLE
 Invalid URL 'URL': No schema supplied. Perhaps you meant http://URL?

### ISSUE THREAD

**Issue by fvnks** [D0N-B0T/OfertasSniper#1]
Hola, tengo el siguiente error 
Invalid URL 'URL': No schema supplied. Perhaps you meant http://URL?, me he quebrado la cabeza tratando de reparar pero no cacho que puede ser.
tienes alguna idea de que puede ser?

**Comment by D0N-B0T** [comment]
Estoy preparando otro codigo que funciona incluso mejor que el que está en esta repo, reemplazará todo asi que ahi lo verás.
